name: Ambiente de testes - boilerplate
on:
  push:
    branches:
      - develop

jobs:
  release:
    name: Obtém o código-fonte e realiza a construção dos pré-requisitos.
    runs-on: [self-hosted]
    services:
      mysql:
        image: mariadb:latest
        env:
          MYSQL_DATABASE: test_database
          MYSQL_HOST: 127.0.0.1
          MYSQL_USER: admin
          MYSQL_PASSWORD: rootpass
          MYSQL_ROOT_PASSWORD: rootpass
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        dependency-stability: [ 'prefer-stable' ]

    steps:
      - uses: actions/checkout@v2

      - name: Install PHP versions
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: fileinfo, libxml, tokenizer, filter, json, phar, pcre, openssl, pdo
          coverage: xdebug

      - name: Get Composer Cache Directory 2
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - uses: actions/cache@v2
        id: actions-cache
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
