name: Ambiente de testes - boilerplate
on:
  push:
    branches:
      - master

jobs:
  release:
    name: Obtém o código-fonte e realiza a construção da aplicação.
    runs-on: self-hosted

    env:
      DB_DATABASE: wordplate
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_HOST: 127.0.0.1
      DB_PORT: 32574
      BROADCAST_DRIVER: log
      MYSQL_ALLOW_EMPTY_PASSWORD: false
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordplate
    services:
      mariadb:
        image: mariadb:10.4
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: wordplate
        ports:
          - 32574:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['8']

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2
