name: Ambiente de testes - boilerplate
on:
  push:
    branches:
      - master

jobs:
  release:
    name: Obtém o código-fonte e realiza a construção da aplicação.
    runs-on: self-hosted
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Executando composer install para dependências do Wordpress
        uses: php-actions/composer@v6
        with:
          php_version: 8
          version: 1
          dev: no
          args: -o --ignore-platform-reqs -d ./headlessCMS
